import React from "react";
import WFooter from "../../Components/Footer/WFooter";
import WComponentNavbar from "../../Components/Navbar/WComponentNavbar";
import './WPrivacyPolicy.scss';

const WPrivacyPolicy = () => {
    return(
        <>
        <WComponentNavbar/>
        <div className='privacy-policy-outer-container'>
        <div className='privacy-policy-container'>
       <div className='privacy-1'>
        <h3 className='privacy-one-heading'>Privacy Policy</h3>
        <p className='privacy-one-title'>Oben Electric Vehicles Private Limited having its registered 
        office at Indiqube Orion, Ground Floor, Sector 2, 24th Main HSR Layout, Harulukunte Village, 
        Begur Hobli Bangalore-560102, Karnataka, India, its affiliates and subsidiaries (“our”, “we”, and “us”) 
        respect the privacy of a natural person (“user”, “you”, “your”), and we are committed to
         protecting it in accordance with the terms of this privacy policy (“Policy”) when you
          access, browse or use our website available at https://www.obenelectric.com/, (“Platform”)
           in relation to the features, products or services offered on the Platform (“Services”).</p>
       </div>
       <div className='privacy-2'>
        <h4 className='privacy-default-heading'>1. General</h4>
        <p className='privacy-default-title'>1.1 This Policy, together with the terms of use (available here: [insert the hyperlink of the Platform’s terms of use]) governs your use of our Platform and/ or Services; describes the types of information we may collect from you or that you may provide to us when you use our Platform and/ or Services and our associated services, and lays down our practices and purposes for collecting, receiving, processing, storing, dealing, using, maintaining, transferring, and disclosing such information.

1.2 This Policy applies to information we collect or receive:
(a) On our Platform;
(b) Via e-mail and other electronic communication between you and us; or
(c) When you use the Services.

1.3  This document is an electronic record in terms of Information Technology Act, 2000 (“Act”) and rules framed thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
       </div>
       <div className='privacy-3'>
       <h4 className='privacy-default-heading'>2. APPLICABILITY AND MODIFICATION OF THE TERMS</h4>
        <p className='privacy-default-title'>2.1  The Agreement may be altered, from time to time, at the sole discretion of Oben, and the Agreement will apply to your visit to and your use of the Platform, as well as to all information provided by you on the Platform at any given point in time.
2.2  The Agreement defines the terms and conditions under which you are allowed to use the Platform.

2.3  We reserve the right to modify or terminate any portion of the Agreement for any reason and at any time.

2.4  You are advised to read the Agreement at regular intervals. Your use of the Platform following any such modification constitutes your agreement to follow and be bound by the Agreement so modified. Any additional terms and conditions, disclaimers, Privacy Policy and other policies applicable to the Platform are also considered as part of the Agreement.

2.5  Your access and use of the Platform will be at the sole discretion of Oben.
</p>
       </div>
       <div className='privacy-4'>
       <h4 className='privacy-default-heading'>3. CONDITIONS OF USE</h4>
        <p className='privacy-default-title'>You must be 18 years of age or older to visit or use the Platform in any manner. By registering, visiting and using the Platform or accepting the terms of this Agreement, you represent and warrant to Oben that you are 18 years of age or older, and that you have the right, authority and capacity to use the Platform and agree to abide by the Agreement.</p>
       </div>

       <div className='privacy-5'>
       <h4 className='privacy-default-heading'>4. LISTING OF CONTENT ON THE PLATFORM​</h4>
        <p className='privacy-default-title'>4.1  The Platform may be linked to the websites of third parties, affiliates, and business partners. In such case Oben has no control over, and is not liable or responsible for the content, accuracy, validity, reliability, quality of such Platforms that are made available through Oben’s Platform. The inclusion of any link on the Platform does not imply that Oben endorses the linked site. You may use the links and these services at your own risk.<br/>

4.2  Oben assumes no responsibility, and shall not be liable for, any damages or viruses that may infect your device on account of your access to, use of, or browsing the Platform or the downloading of any material, data, text, images, video content, or audio content from the Platform.
</p>
       </div>

       <div className='privacy-6'>
       <h4 className='privacy-default-heading'>5. CONTENT OWNERSHIP</h4>
        <p className='privacy-default-title'>5.1  Any information that is published by Oben, directly or indirectly, 
        shall belong to Oben. Copying of the copyrighted content published
         by Oben on the Platform for any commercial purpose or to earn profit
          will be a violation of the copyright law and Oben reserves its rights
           to take action under applicable law accordingly.<br/>
           5.2  The contents of the Platform, information, text, graphics, images, logos, button icons, software code, design, and the collection, arrangement and assembly of content on the Platform, are the property of Oben and are protected under copyright, trademark and other applicable laws. You shall not modify, reproduce, display, publicly perform, distribute, or otherwise use such content in any way for any public or commercial purpose or for personal gain.
           </p>
       </div>

       <div className='privacy-7'>
       <h4 className='privacy-default-heading'>6. USER WARRANTIES AND RESTRICTIONS</h4>
        <p className='privacy-default-title'>
        6.1  You represent and warrant that:
        <ol>
          <li>your use of the Platform will not violate any applicable law or regulation</li>
          <li>any content you post or publish on the Platform or any information you provide
             to us does not infringe any third-party intellectual property or privacy
              rights including SPDI Rules; or</li>
          <li>all information that is submitted to us by you is true, accurate and lawful.</li>
        </ol>
        6.2   By using the Platform, you agree that any information shared by you 
        with Oben or anyone else using the Platform will be subject to our Privacy
         Policy. Oben shall not be responsible in any manner for the authenticity 
         or correctness of such information supplied by you to Oben.
        <br/>
         6.3   If you provide any information that is untrue, inaccurate,
          or incomplete (or becomes untrue, inaccurate, or incomplete), or
           Oben has reasonable grounds to suspect that such information is 
           untrue, inaccurate, or incomplete, Oben has the right to discontinue
            the use of Platform to you, at its’ sole discretion.
        </p>
       </div>

       <div className='privacy-8'>
       <h4 className='privacy-default-heading'>7. COMMUNICATION AND UNSUBSCRIPTION</h4>
        <p className='privacy-default-title'>7.1   By accepting the Terms, you also accept to receive news,
         updates, offers/campaign related SMS, to the mobile phone number 
         provided by you. By accessing and using the Platform and/ or verifying 
         your contact number with us, you explicitly consent to receive such 
         communications (through call, SMS, email or other digital and electronic means)
          from us and/or our authorized representatives regarding any new services 
          or offerings.<br/>
          7.2   You can unsubscribe/opt-out from receiving such marketing/promotional
           communications, newsletters and other notifications from us
            at any time by following the instructions set out in such communications.<br/>
            7.3   You undertake and agree to provide your co-operation to Oben,
             as and when Oben may contact you through telephone, e-mail, SMS,
              or any other electronic means of communication for:<br></br>
              <ol>
                <li>obtaining review or feedback about the Platform; and</li>
                <li>resolving any complaints or queries regarding your use of the Platform.</li>
              </ol>

          </p>
       </div>

       <div className='privacy-9'>
       <h4 className='privacy-default-heading'>8. INTELLECTUAL PROPERTY RIGHTS</h4>
        <p className='privacy-default-title'>8.1  The contents of the Platform are protected by 
        intellectual property laws of India including without limitation
         to trademark and copyright laws. Reproduction, retransmission,
          public and/or commercial use of any or all the material on the 
          Platform are prohibited. The logos, service marks and trademarks
           displayed on the Platform are the property of Oben or have been
            licensed to Oben by the owners for use. You may use this material
             only as expressly authorized by Oben and shall not copy, transmit
              or create derivative works of such material without express authorization
               from Oben.<br/>
               8.2  You acknowledge and agree that you shall not upload, post, reproduce
                or distribute any content on or through the Platform that is protected 
                by copyright or another proprietary right of a third party, without
                 obtaining the permission of the owner of such right. Any copyrighted
                  or other proprietary content distributed on or through the Platform 
                  with the consent of the owner must contain the appropriate copyright
                   or other proprietary rights notice. The unauthorized submission or
                    distribution of copyrighted or other proprietary content is illegal
                     and could subject you to personal liability or criminal prosecution.
                      Nothing on the Platform should be construed as granting, by implication,
                       estoppels, or otherwise, any license or right to use any trademarks
                        without written permission from Oben.
               </p>
       </div>

       <div className='privacy-10'>
       <h4 className='privacy-default-heading'>9. DISCLAIMER OF WARRANTIES</h4>
        <p className='privacy-default-title'>9.1   All information available on the Platform, (“Platform Information”) 
        is provided on the condition that you will make an independent determination
         in respect of its accuracy, completeness, usefulness or suitability before 
         using such Platform Information and Oben will not be responsible for the same.
          Further Oben will not be responsible or liable in any manner for any data added, 
          provided, stored or managed by you including all personal data. <br/>
          9.2  The Platform Information could include inaccuracies or typographical
           errors. Oben has endeavoured to ensure that all the Platform Information
            on the Platform is correct, but Oben neither warrants nor makes any 
            representations regarding the quality, accuracy or completeness of
             any data or information contained therein.<br/>
             9.3   All Platform Information is provided to you on an ‘as is’ basis, without
              warranty or guarantee of any kind, either express or implied, including, but
               not limited to implied warranties of merchantability and fitness for a 
               particular purpose, title, non-infringement, security or accuracy.
          </p>
       </div>

       <div className='privacy-11'>
       <h4 className='privacy-default-heading'>10. LIMITATION OF LIABILITY​</h4>
        <p className='privacy-default-title'>10.1   Oben makes no warranty, express or implied,
         concerning the Platform or its contents and disclaims all liability, 
         responsibility or any other claim, whatsoever, in respect of any loss,
          whether direct or consequential, to you or any other person, arising 
          out of or from the use of the Platform Information or any suggestion
           or opinion given or expressed by Oben on Platform.<br/>
           10.2  You undertake and agree that in no event shall Oben be liable for 
           any direct, indirect, punitive, incidental, special, consequential damages
            or any other damages resulting from:<br/>
            <ol>
              <li>your use, delay in use or the inability to use the Platform;</li>
              <li>unauthorized access to or alteration of your data;</li>
              <li>any other matter including, without limitation to the damages for
                 loss of data or profits, arising out of or in any way connected
                  with the use or performance of the Platform.</li>
            </ol>
            10.3   You understand and agree that any material and/or data downloaded 
            or otherwise obtained through the Platform is done entirely at your
            discretion and risk and you shall be solely responsible for any damage
            to your computer systems or loss of data that results from the download
            of such material and/or data.
           </p>
       </div>

       <div className='privacy-12'>
       <h4 className='privacy-default-heading'>11. INDEMNITY</h4>
        <p className='privacy-default-title'>If Oben determines through feedback or otherwise
         that you have provided fraudulent, inaccurate, incomplete
          or false information, Oben reserves the right to immediately
           suspend your access to the Platform. You shall be liable to
            indemnify Oben and its partners for any losses incurred as a result
             of your misrepresentations or fraudulent feedback that has adversely
              affected Oben, its partners or its users.<br/><br></br>
              You hereby undertake and agree to indemnify and hold harmless Oben,
               its’ affiliates, officers, directors, employees, consultants,
                licensors, agents, representatives from any and all third-party claims, 
                losses, liability, damages, and/or costs (including reasonable attorney fees and costs) 
                arising from your access to or use of Platform, violation of this Agreement, 
                or infringement of any intellectual property or other rights of any person or
                 entity. Oben shall notify you of any such claim, loss, liability, or demand, 
                 and in addition to your foregoing obligations, you agree to provide us with
                  reasonable assistance, at your expense, in defending any such claim, loss,
                   liability, damage, or cost.
              </p>
       </div>

       <div className='privacy-13'>
       <h4 className='privacy-default-heading'>12. APPLICABLE LAW AND DISPUTE SETTLEMENT​</h4>
        <p className='privacy-default-title'>You agree that this Agreement and any contractual obligation
         arising between you and Oben will be governed by the laws of India.
          The courts at Bengaluru, Karnataka shall have exclusive jurisdiction
           over any disputes arising out of or in connection with this Agreement,
            your use of the Platform and the information provided therein.</p>
       </div>

       <div className='privacy-14'>
       <h4 className='privacy-default-heading'>13. SEVERABILITY</h4>
        <p className='privacy-default-title'>If any term of this Agreement is held to
         be invalid or unenforceable, that term shall be reformed
          to achieve as nearly as possible the same effect as the original term,
           and the remainder of this Agreement shall remain in full force.</p>
       </div>

       <div className='privacy-15'>
       <h4 className='privacy-default-heading'>14. WAIVER​</h4>
        <p className='privacy-default-title'>Any waiver by Oben of a breach or threatened 
        breach of this Agreement by you shall not be construed as a waiver of any 
        subsequent breach by you. Any waiver must be in writing and signed by Oben.</p>
       </div>

       <div className='privacy-16'>
       <h4 className='privacy-default-heading'>15. GRIEVANCE REDRESSAL​</h4>
        <p className='privacy-default-title'>In case, you have any questions, grievance or complaints about these Terms, or the Platform, you may contact our grievance officer on the below mentioned details:<br/>
<b>Addressed to:</b>      Grievance officer<br/>
<b>Email Address:</b>     grievance@obenelectric.com<br/>
<b>Contact Address:</b> Indiqube Orion, Ground Floor, Sector 2, 24th Main HSR Layout, 
Harulukunte Village, Begur Hobli Bangalore-560102, Karnataka, India
</p>
       </div>
    </div>
        </div>
        <WFooter/>
        </>
    )
}

export default WPrivacyPolicy;