import React from 'react'
import WFooter from '../../Components/Footer/WFooter';
import WComponentNavbar from '../../Components/Navbar/WComponentNavbar';
import './WTermsAndConditions.scss';


const WTermsConditions = () => {
    return(
        <>
        <WComponentNavbar/>
        <div className='wterms-and-conditions-outer-container'>
        <div className='wterms-condition-container'>
       <div className='wterms-one'>
        <h3 className='wterms-one-heading'>Terms & Conditions</h3>
        {/* <p className='terms-one-title'>Agnes Blom Oliver Blom spoilervarning fulfillment revis. Eur Emanuel Norberg, i fiskpedikyr gonnabe, liksom loba sälyktiga, zlatanera ett telen för att Ingegerd Öberg medan Jörgen Björklund i see now buy now asade, Sten Ek dekavavis. Outbound marketing rens i Barbro Eklund Lovisa Olsson, kroren i pona. Julia Mårtensson belingar orade Karolina Öberg Maria Lundin i Ingrid Jensen pyramidmatta språkplikt eller fesk. Suprass effektiv pultvätta fasamma osaning därför att teneling överklassafari cringe. SEO mobilvantar. Kvasining hexadiktig, mov Alexandra Nordin i kolyr, gade Viola Henriksson. Egogöledes growth hacking enveckasförsvar ibel Tintingate, har dobelt plattfilm. </p> */}
       </div>
       <div className='wterms-two'>
        <h4 className='wterms-default-heading'><b>1. ACCEPTANCE OF TERMS OF USE</b></h4>
        <p className='wterms-default-title'>1.1  Oben Electric Vehicles Private Limited having its registered
         office at Indiqube Orion, Ground Floor, Sector 2, 24th Main HSR Layout, Harulukunte Village, Begur Hobli
          Bangalore-560102, Karnataka, India, its affiliates and subsidiaries (“we”, “us”, “Oben”) is the author
           and publisher of the internet resource https://www.obenelectric.com/ and the information, content, products
            and services available at such internet resource or any other social media posting by Oben (collectively as “Platform”).
             Please read these terms of use (“Terms”) and the privacy policy available
              at [insert the hyperlink of the Platform’s privacy policy] (“Privacy Policy”) carefully, before you decide to access the Platform.
               These Terms and the Privacy Policy together constitute a legal agreement (“Agreement”) between Oben and a natural or legal person 
               who accesses and/or uses the Platform in any manner (“you” or “your”).</p>
       </div>
       <div className='wterms-three'>
       {/* <h4 className='terms-default-heading'>Lorem, ipsum dolor.</h4> */}
        <p className='wterms-default-title'>1.2  By accessing the Platform, you unequivocally and irrevocably accept and agree to abide
         by the Agreement. The Agreement supersedes all previous oral and 
         written terms and conditions (if any) communicated to you. If you do
          not agree to these Terms, in whole or in part, please do not access
           the Platform.</p>
       </div>
       <div className='wterms-four'>
       {/* <h4 className='terms-default-heading'>Lorem, ipsum dolor.</h4> */}
        <p className='wterms-default-title'>1.3  This document is an electronic record in terms of Information Technology Act, 2000 (“Act”) and
         rules framed thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
       </div>
    </div>
        </div>
        <WFooter/>
        </>
    )
}

export default WTermsConditions;